---
name: Run CI/CD Pipeline for docker job
on:
  push:
    branches:
      # - main
      - cicd-pipeline
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: log into dockerhub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |                                    # your dockerhub_username/your-image-name:latest or version number like :v1.1.0
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nickos-website:v1.0.0 .

    # Push the Docker image to Docker Hub
      - name:  Push Docker Image to Docker Hub
        # uses: docker/build-push-actions@v2
        run: |
          docker tag nickos-app ${{ secrets.DOCKERHUB_USERNAME }}/nickos-website:v1.0.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nickos-website:v1.0.0